services:
  db:
    container_name: mentovc_db
    image: postgres:14.17
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5439:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - postgres
    volumes:
      - volume:/var/lib/postgresql/data

volumes:
  volume:

networks:
  postgres:
    driver: bridge